name: Pack heading Release

on:
  push:
    tags: [ "heading" ]
  pull_request:
    tags: [ "heading" ]

jobs:
  
  release:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Pack
      run: |
        chmod +x ./PackReleaseZip.py
        ./PackReleaseZip.py
      shell: bash
    
    - name: Update Release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./ShareTitle.zip
        tag: heading
        release: heading
        prerelease: false
